# Generated by Django 4.0 on 2023-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resep',
            name='takaran',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
