# Generated by Django 4.0 on 2023-08-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resep', '0002_resep_takaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resep',
            old_name='judul_resep',
            new_name='nama_resep',
        ),
    ]
