# Generated by Django 4.0 on 2023-08-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resep', '0003_rename_judul_resep_resep_nama_resep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resep',
            name='takaran',
        ),
    ]
